import logging

def generate_structured_prompt(user_prompt: str, language: str = "python"):
    """
    Generates a structured prompt for the given user input.
    This is a placeholder using Qwen model from global instance.
    """
    from app.model_manager import global_pipeline

    logging.info("Generating structured prompt...")
    # This is just an example prompt; adjust to your TUA logic
    prompt = f"Language: {language}\nTask: {user_prompt}\nGenerate a structured prompt."
    response = global_pipeline(prompt, max_new_tokens=500, temperature=0.3)

    structured_prompt = response[0]['generated_text']
    return {
        "structured_prompt": structured_prompt,
        "method_used": "Qwen1.5-7B-Chat",
        "constraints": "Generated by TUA"
    }
